package com.garderie.types.security.auth.permissions;

public enum ActionPermissions {

    ADD_OWNER,
    ADD_PARENT,
    ADD_TEACHER,
    UPDATE_TEACHER,
    ADD_ORGANISATION,
    ADD_CLASSROOM,
    UPDATE_CLASSROOM,
    GET_CLASSROOMS,
    DELETE_CLASSROOM,
    ADD_STUDENT_TO_CLASSROOM,
    REMOVE_STUDENT_FROM_CLASSROOM,
    ADD_ACTIVITY,
    ADD_PICTURE,
    VIEW_ACTIVITY,
    VIEW_FEED,
    ADD_CHILD,
    GET_ALL_CHILDRENS,
    UPDATE_CHILD;


}
